---
title: "Title"
author: "Sharon Allman, Diego Mamanche Castellano & Ke-Li Chiu"
date: "08/04/2020"
output:
  pdf_document:
    latex_engine: xelatex
abstract: "The abstract"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, include = FALSE, cache = TRUE)## R Markdown
```

```{r echo=FALSE, include=FALSE, message=FALSE}
#Set up the environment
library(readxl)
library(dplyr)
library(tidyr)
library(ggplot2)
library(reshape2)
library(stringr)
library(knitr)
library(tidyverse)
library(broom)
library(huxtable)
library(jtools)
#setwd("~/Experimental Design for Data Science/ProblemSet4")
```

```{r echo=FALSE, include=FALSE, message=FALSE}
### Upload and read datasets
alcohol_crime_data <- read.csv("P01_Age_Profile_of_Arrest_Rates_1979-2006.csv")
### Filter dataset to contain data only from age 19 to 22 
alcohol_crime_data <- alcohol_crime_data %>% filter(days_to_21 %in% (-730:730))
```

```{r echo=FALSE}
colnames(alcohol_crime_data)
```
```{r echo=FALSE}
### Violent crime rate regression discontinuity graph
alcohol_crime_data %>% 
  ggplot(aes(x = days_to_21,
             y = violent_r)) +
  geom_point(alpha = 0.2) +
  geom_smooth(data = alcohol_crime_data %>% filter(days_to_21 >= 0), 
              method='lm',
              color = "black") +
  geom_smooth(data = alcohol_crime_data %>% filter(days_to_21 < 0), 
              method='lm',
              color = "black") +
  theme_minimal() +
  labs(x = "Days to 21",
       y = "Violent Crime Arrest Rates")
```
```{r echo=FALSE}
### Rape crime arrest rate regression discontinuity graph
alcohol_crime_data %>% 
  ggplot(aes(x = days_to_21,
             y = rape_r)) +
  geom_point(alpha = 0.2) +
  geom_smooth(data = alcohol_crime_data %>% filter(days_to_21 >= 0), 
              method='lm',
              color = "black") +
  geom_smooth(data = alcohol_crime_data %>% filter(days_to_21 < 0), 
              method='lm',
              color = "black") +
  theme_minimal() +
  labs(x = "Days to 21",
       y = "Rape crime arrest rate")

### Murder crime arrest rate regression discontinuity graph
alcohol_crime_data %>% 
  ggplot(aes(x = days_to_21,
             y = murder_r)) +
  geom_point(alpha = 0.2) +
  geom_smooth(data = alcohol_crime_data %>% filter(days_to_21 >= 0), 
              method='lm',
              color = "black") +
  geom_smooth(data = alcohol_crime_data %>% filter(days_to_21 < 0), 
              method='lm',
              color = "black") +
  theme_minimal() +
  labs(x = "Days to 21",
       y = "Murder crime arrest rate")

### Manslaughter crime arrest rate regression discontinuity graph
alcohol_crime_data %>% 
  ggplot(aes(x = days_to_21,
             y = manslaughter_r)) +
  geom_point(alpha = 0.2) +
  geom_smooth(data = alcohol_crime_data %>% filter(days_to_21 >= 0), 
              method='lm',
              color = "black") +
  geom_smooth(data = alcohol_crime_data %>% filter(days_to_21 < 0), 
              method='lm',
              color = "black") +
  theme_minimal() +
  labs(x = "Days to 21",
       y = "Manslaughter crime arrest rate")

### Robbery crime arrest rate regression discontinuity graph
alcohol_crime_data %>% 
  ggplot(aes(x = days_to_21,
             y = robbery_r)) +
  geom_point(alpha = 0.2) +
  geom_smooth(data = alcohol_crime_data %>% filter(days_to_21 >= 0), 
              method='lm',
              color = "black") +
  geom_smooth(data = alcohol_crime_data %>% filter(days_to_21 < 0), 
              method='lm',
              color = "black") +
  theme_minimal() +
  labs(x = "Days to 21",
       y = "Robbery crime arrest rate")

### Aggregaved assault crime arrest rate regression discontinuity graph
alcohol_crime_data %>% 
  ggplot(aes(x = days_to_21,
             y = aggravated_assault_r)) +
  geom_point(alpha = 0.2) +
  geom_smooth(data = alcohol_crime_data %>% filter(days_to_21 >= 0), 
              method='lm',
              color = "black") +
  geom_smooth(data = alcohol_crime_data %>% filter(days_to_21 < 0), 
              method='lm',
              color = "black") +
  theme_minimal() +
  labs(x = "Days to 21",
       y = "Aggregaved assault crime arrest rate")
```

```{r echo=FALSE}
### Violent crime rate Linear regression
alcohol_crime_data <- 
  alcohol_crime_data %>% 
  mutate(twentyone_and_over = if_else(days_to_21 > 0, 0, 1)) 
lm(violent_r ~ days_to_21 + twentyone_and_over, data = alcohol_crime_data) %>% 
  tidy()
```

```{r echo=FALSE}
### Rape crime rate Linear regression
alcohol_crime_data <- 
  alcohol_crime_data %>% 
  mutate(twentyone_and_over = if_else(days_to_21 < 0, 0, 1 )) 
lm(rape_r ~ days_to_21 + twentyone_and_over, data = alcohol_crime_data) %>% 
  tidy()
```
```{r echo=FALSE}
### Murder crime rate Linear regression
alcohol_crime_data <- 
  alcohol_crime_data %>% 
  mutate(twentyone_and_over = if_else(days_to_21 < 0, 0, 1)) 
lm(murder_r ~ days_to_21 + twentyone_and_over, data = alcohol_crime_data) %>% 
  tidy()
```

```{r echo=FALSE}
### Manslaughter crime rate Linear regression
alcohol_crime_data <- 
  alcohol_crime_data %>% 
  mutate(twentyone_and_over = if_else(days_to_21 < 0, 0, 1)) 
lm(manslaughter_r ~ days_to_21 + twentyone_and_over, data = alcohol_crime_data) %>% 
  tidy()
```

```{r echo=FALSE}
### Robbery crime rate Linear regression
alcohol_crime_data <- 
  alcohol_crime_data %>% 
  mutate(twentyone_and_over = if_else(days_to_21 < 0, 0, 1)) 
lm(robbery_r ~ days_to_21 + twentyone_and_over, data = alcohol_crime_data) %>% 
  tidy()
```
```{r echo=FALSE}
### Assault crime rate Linear regression
alcohol_crime_data <- 
  alcohol_crime_data %>% 
  mutate(twentyone_and_over = if_else(days_to_21 < 0, 0, 1)) 
lm(aggravated_assault_r ~ days_to_21 + twentyone_and_over, data = alcohol_crime_data) %>% 
  tidy()
```

